### ISSUE TITLE
About the range of values for BIGINT

### ISSUE THREAD

**Issue by lutengda** [cnosdb/cnosdb#1087]
I created a table like this：
![image](https://user-images.githubusercontent.com/50371898/230834892-0a898166-b376-477c-b042-77693f81f706.png)

I get this error when I execute the insert statement：
`INSERT m4(TIME, t0, f1) VALUES(CAST (1672301798050000000 AS TIMESTAMP), 'n꓃DH~B ', 9223372036854775807),(CAST (1672301798060000000 AS TIMESTAMP), '', -9223372036854775808),(CAST (1672301798070000000 AS TIMESTAMP), 'gc.', 0);`
![image](https://user-images.githubusercontent.com/50371898/230835463-0d7141c2-7f60-4626-b8ef-17a2942bde75.png)

I query the signed 8 bytes of type int value range is -9223372036854775808 to 9223372036854775807
I think values in this range can be inserted normally

**Comment by yukkit** [comment]
In CnosDB, `-9223372036854775808` will be seen as a UnaryOperator(-, Int64(9223372036854775808)), but 9223372036854775808 exceeds the maximum value of i64, so 9223372036854775808 will be parsed as f64, and finally -9223372036854775808 is considered an f64 type.

In some databases, select -9223372036854775808 returns the correct i64 value, some databases will report errors, and some databases will overflow (CnosDB).

We won't be correcting this behavior in the short term because it's irrelevant. This can be considered normal behavior or a known issue.
