### ISSUE TITLE
Support for IN operator in CnosQL

### ISSUE THREAD

**Issue by muninshen** [cnosdb/cnosdb#305]
**Is your feature request related to a problem? Please describe.**
In CnosQL, if I filter the results, I have to use OR, which is verbose:

`SELECT * FROM test WHERE region = 'ny' OR region = 'ln' OR region = 'hk' OR region = 'sh'`

**Describe the solution you'd like**
Could we have something similar to below:

`SELECT * FROM test WHERE region IN ( 'ny', 'ln', 'hk', 'sh') `

**Describe alternatives you've considered**
not yet

**Use case**
Current solution is verbose.

**Comment by IvanGao01** [comment]
Can you list more use cases? I don't think it's necessary to add "in" if there is only some duplicate SQL code, Because our design philosophy is that the simpler the better, adding more syntactic sugar will only make the product more complex， If it is a habit that needs to be adapted to standard SQL users, this is indeed a reason to add him, but is it really necessary?

**Comment by zipper-meng** [comment]
Want to filter data by one tag? Regular expression may help you:
`SELECT * FROM test WHERE region =~ /^ny|ln|hk|sh$/`
